
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# build settings
markdown: kramdown
remote_theme: daattali/beautiful-jekyll